// Generated by gfwlist2pac in precise mode
// https://github.com/clowwindy/gfwlist2pac

// var proxy = "SOCKS5 127.0.0.1:1086; SOCKS 127.0.0.1:1086; DIRECT;";
var proxy = "SOCKS5 127.0.0.1:1086";
var direct = 'DIRECT';

// rules that define sites need proxy
var proxy_rules = [
  "(https|http)://[^/]*wikitionary\.org.*",
  "(https|http)://[^/]*wikipedia\.org.*",
  "(https|http)://[^/]*stackoverflow[^/]*",
  "(https|http)://[^/]*stackexchange[^/]*",
  "(https|http)://[^/]*tweeter[^/]*",
  "(https|http)://[^/]*facebook[^/]*",
  "(https|http)://[^/]*youtube[^/]*",
  "(https|http)://[^/]*youtu.be[^/]*",
  "(https|http)://[^/]*google[^/]*",
  "(https|http)://[^/]*amazon[^/]*",
  "(https|http)://[^/]*github[^/]*",
  "(https|http)://[^/]*facebook[^/]*",
  "(https|http)://[^/]*justmysocks\.net.*",
  "(https|http)://[^/]*medium\.com.*",
  "(https|http)://[^/]*google\.(ac|ad|ae|af|al|am|as|at|az|ba|be|bf|bg|bi|bj|bs|bt|by|ca|cat|cd|cf|cg|ch|ci|cl|cm|co.ao|co.bw|co.ck|co.cr|co.id|co.il|co.in|co.jp|co.ke|co.kr|co.ls|co.ma|com|com.af|com.ag|com.ai|com.ar|com.au|com.bd|com.bh|com.bn|com.bo|com.br|com.bz|com.co|com.cu|com.cy|com.do|com.ec|com.eg|com.et|com.fj|com.gh|com.gi|com.gt|com.hk|com.jm|com.kh|com.kw|com.lb|com.ly|com.mm|com.mt|com.mx|com.my|com.na|com.nf|com.ng|com.ni|com.np|com.om|com.pa|com.pe|com.pg|com.ph|com.pk|com.pr|com.py|com.qa|com.sa|com.sb|com.sg|com.sl|com.sv|com.tj|com.tr|com.tw|com.ua|com.uy|com.vc|com.vn|co.mz|co.nz|co.th|co.tz|co.ug|co.uk|co.uz|co.ve|co.vi|co.za|co.zm|co.zw|cv|cz|de|dj|dk|dm|dz|ee|es|eu|fi|fm|fr|ga|ge|gg|gl|gm|gp|gr|gy|hk|hn|hr|ht|hu|ie|im|iq|is|it|it.ao|je|jo|kg|ki|kz|la|li|lk|lt|lu|lv|md|me|mg|mk|ml|mn|ms|mu|mv|mw|mx|ne|nl|no|nr|nu|org|pl|pn|ps|pt|ro|rs|ru|rw|sc|se|sh|si|sk|sm|sn|so|sr|st|td|tg|tk|tl|tm|tn|to|tt|us|vg|vn|vu|ws).*",
  "(https|http)://[^/]*apache\.(com|org).*",
  "(https|http)://[^/]*sourceforge\.(net|com).*",
  "(https|http)://[^/]*stackoverflow\.(com|org).*",
  "(https|http)://[^/]*quora\.com.*",
  "(https|http)://[^/]*atlassian\.com.*",
  "(https|http)://[^/]*superuser\.com.*",
  "(https|http)://[^/]*poe\.com.*",
  "(https|http)://[^/]*inkscape\.org.*",
  "(https|http)://[^/]*gceasy\.io.*",
  "(https|http)://[^/]*acm\.org.*",
  "(https|http)://[^/]*almworks[^/]*",
  "(https|http)://[^/]*terraform[^/]*",
  "(https|http)://[^/]*chrome[^/]*",
  "(https|http)://[^/]*reddit[^/]*",
  "(https|http)://[^/]*openai\.com.*",
  "(https|http)://[^/]*chatgpt\.com.*",
  ".*slack\.com.*",
  "(https|http)://[^/]*grammarly\.*",
  "(https|http)://[^/]*huggingface[^/]*",
  "(https|http)://[^/]*bloomberg[^/]*",
  "(https|http)://x.com.*",
];

function matchAnyProxyRules(url, host) {
  for (var r of proxy_rules) {
    if (url.match(r)) return true;
  }
  return false;
}

function FindProxyForURL(url, host) {
  console.log("check proxy url="+url+" host="+host);
  if (matchAnyProxyRules(url, host)) {
    return proxy;
  }
  return direct;
}

// vim: et ts=2 sw=2:
